/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bracket: typeof import('./src/components/Bracket.vue')['default']
    BracketContainer: typeof import('./src/components/BracketContainer.vue')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiPlus: typeof import('~icons/mdi/plus')['default']
    MatchUp: typeof import('./src/components/MatchUp.vue')['default']
    Round: typeof import('./src/components/Round.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TournamentTree: typeof import('./src/components/TournamentTree.vue')['default']
  }
}
