// Generated by scripts/generate-icons.mjs from frontend/icons.json.
// Do not edit this file directly.

export const kirbbyIconNames = Object.freeze({
  "refresh": "refresh-cw",
  "save": "save",
  "delete": "trash-2",
  "close": "x",
  "favorite": "star",
  "navMenu": "menu",
  "sidebarCollapse": "panel-left-close",
  "sidebarUncollapse": "panel-left-open",
  "add": "plus",
  "search": "search",
  "archive": "archive",
  "settings": "settings",
});

export const kirbbyIconFiles = Object.freeze({
  "refresh": "refresh.svg",
  "save": "save.svg",
  "delete": "delete.svg",
  "close": "close.svg",
  "favorite": "favorite.svg",
  "navMenu": "nav-menu.svg",
  "sidebarCollapse": "sidebar-collapse.svg",
  "sidebarUncollapse": "sidebar-uncollapse.svg",
  "add": "add.svg",
  "search": "search.svg",
  "archive": "archive.svg",
  "settings": "settings.svg",
});

export const kirbbyIconPaths = Object.freeze({
  "refresh-cw": "<path d=\"M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8\"/><path d=\"M21 3v5h-5\"/><path d=\"M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16\"/><path d=\"M8 16H3v5\"/>",
  "save": "<path d=\"M15.2 3a2 2 0 0 1 1.4.6l3.8 3.8a2 2 0 0 1 .6 1.4V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z\"/><path d=\"M17 21v-7a1 1 0 0 0-1-1H8a1 1 0 0 0-1 1v7\"/><path d=\"M7 3v4a1 1 0 0 0 1 1h7\"/>",
  "trash-2": "<path d=\"M10 11v6\"/><path d=\"M14 11v6\"/><path d=\"M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6\"/><path d=\"M3 6h18\"/><path d=\"M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2\"/>",
  "x": "<path d=\"M18 6 6 18\"/><path d=\"m6 6 12 12\"/>",
  "star": "<path d=\"M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z\"/>",
  "menu": "<path d=\"M4 5h16\"/><path d=\"M4 12h16\"/><path d=\"M4 19h16\"/>",
  "panel-left-close": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\"/><path d=\"M9 3v18\"/><path d=\"m16 15-3-3 3-3\"/>",
  "panel-left-open": "<rect width=\"18\" height=\"18\" x=\"3\" y=\"3\" rx=\"2\"/><path d=\"M9 3v18\"/><path d=\"m14 9 3 3-3 3\"/>",
  "plus": "<path d=\"M5 12h14\"/><path d=\"M12 5v14\"/>",
  "search": "<path d=\"m21 21-4.34-4.34\"/><circle cx=\"11\" cy=\"11\" r=\"8\"/>",
  "archive": "<rect width=\"20\" height=\"5\" x=\"2\" y=\"3\" rx=\"1\"/><path d=\"M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8\"/><path d=\"M10 12h4\"/>",
  "settings": "<path d=\"M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/>",
});

export function iconName(name) {
  return kirbbyIconNames[name] || name;
}

export function icon(name, className = "icon") {
  const resolvedName = iconName(name);
  return `<span data-kirbby-icon="${resolvedName}" class="${className}" aria-hidden="true"></span>`;
}

export function svgIcon(name, className = "icon") {
  const resolvedName = iconName(name);
  const paths = kirbbyIconPaths[resolvedName];

  if (!paths) {
    return "";
  }

  return `<svg class="${className}" data-kirbby-icon-name="${resolvedName}" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round" focusable="false">${paths}</svg>`;
}

export function mountIcons(root = document) {
  root.querySelectorAll("[data-kirbby-icon]").forEach((placeholder) => {
    const name = placeholder.getAttribute("data-kirbby-icon");
    const className = placeholder.getAttribute("class") || "icon";
    const wrapper = document.createElement("span");

    wrapper.innerHTML = svgIcon(name, className);
    placeholder.replaceWith(wrapper.firstElementChild || document.createTextNode(""));
  });
}
